# Generated by Django 5.2.8 on 2025-12-06 11:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=100, null=True)),
                ('job_role', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('social_media', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(blank=True, choices=[('new', 'New'), ('lost', 'Lost'), ('won', 'Won')], default='new', max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('lead_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('nurturing_stage', models.CharField(blank=True, choices=[('hot', 'Hot - Highly Interested'), ('warm', 'Warm - Moderately Interested'), ('cold', 'Cold - Not Interested')], default='warm', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='api.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_partner', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('is_module_user', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clients', models.ManyToManyField(blank=True, related_name='lists', to='api.client')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lists', to='api.folder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name for identification', max_length=255, unique=True)),
                ('html_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='HTML content of the email', null=True)),
                ('plain_text_content', models.TextField(blank=True, help_text="Plain text version for email clients that don't support HTML", null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('total_sent', models.PositiveIntegerField(default=0, help_text='Total emails sent using this template')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('variables', models.JSONField(blank=True, default=list, help_text="JSON list of available template variables e.g., ['{{name}}', '{{email}}', '{{link}}']")),
                ('thumbnail', models.ImageField(blank=True, help_text='Template preview thumbnail', null=True, upload_to='email_templates/thumbnails/')),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['status'], name='api_templat_status_0d5895_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=255)),
                ('campaign_type', models.CharField(choices=[('newsletter', 'Newsletter'), ('transactional', 'Transactional'), ('promotional', 'Promotional'), ('automated', 'Automated')], default='promotional', max_length=50)),
                ('subject_line', models.CharField(default='No Subject', max_length=255)),
                ('preview_text', models.CharField(blank=True, max_length=500)),
                ('custom_content', models.TextField(blank=True, help_text='Optional override HTML/text content', null=True)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('reply_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('custom_headers', models.JSONField(blank=True, default=dict)),
                ('enable_tracking', models.BooleanField(default=True)),
                ('track_opens', models.BooleanField(default=True)),
                ('track_clicks', models.BooleanField(default=True)),
                ('email_format', models.CharField(choices=[('html', 'HTML'), ('text', 'Plain Text'), ('both', 'Both')], default='both', max_length=10)),
                ('opportunities', models.JSONField(blank=True, default=dict)),
                ('test_email_recipients', models.TextField(blank=True, help_text='Comma-separated test emails')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('save_as_draft', 'Save as Draft'), ('send_test_email', 'Send Test Email'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('paused', 'Paused'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('selected', models.BooleanField(default=False)),
                ('template_variables', models.JSONField(blank=True, default=dict, help_text='JSON object with template variable values')),
                ('contact_lists', models.ManyToManyField(blank=True, related_name='campaigns', to='api.list')),
                ('do_not_send_lists', models.ManyToManyField(blank=True, related_name='excluded_campaigns', to='api.list')),
                ('do_notsent_lists', models.ManyToManyField(blank=True, related_name='do_notsent_lists', to='api.list')),
                ('sent_lists', models.ManyToManyField(blank=True, related_name='sent_list', to='api.list')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='api.template')),
            ],
            options={
                'verbose_name': 'Email Campaign',
                'verbose_name_plural': 'Email Campaigns',
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('unsubscribed', 'Unsubscribed')], default='pending', max_length=20)),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='api.emailcampaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_recipients', to='api.client')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('campaign', 'contact')},
            },
        ),
    ]
