# Generated by Django 5.2.8 on 2025-12-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('lead_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('nurturing_stage', models.CharField(blank=True, choices=[('hot', 'Hot - Highly Interested'), ('warm', 'Warm - Moderately Interested'), ('cold', 'Cold - Not Interested')], default='warm', max_length=10, null=True)),
                ('client', models.CharField(blank=True, max_length=100, null=True)),
                ('job_role', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('social_media', models.JSONField(blank=True, null=True)),
                ('media_url', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
