# Generated by Django 5.2.8 on 2025-12-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('lost', 'Lost'), ('won', 'Won')], default='new', max_length=50, null=True),
        ),
    ]
