# Generated by Django 5.2.8 on 2025-12-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcampaign',
            name='contact_lists',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='do_not_send_lists',
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='bcc_lists',
            field=models.ManyToManyField(blank=True, related_name='bcc_campaigns', to='api.list'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='cc_lists',
            field=models.ManyToManyField(blank=True, related_name='cc_campaigns', to='api.list'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='custom_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='email_format',
            field=models.CharField(choices=[('html', 'HTML'), ('text', 'Plain Text'), ('both', 'Both')], default='both', max_length=10),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='enable_tracking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='reply_to',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='track_clicks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='track_opens',
            field=models.BooleanField(default=True),
        ),
    ]
