# Generated by Django 5.2.8 on 2025-12-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_remove_client_company_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='media_url',
        ),
    ]
