# Generated by Django 5.2.8 on 2025-12-05 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_emailcampaign_contact_lists_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailcampaign',
            old_name='bcc_lists',
            new_name='do_notsent_lists',
        ),
        migrations.RenameField(
            model_name='emailcampaign',
            old_name='cc_lists',
            new_name='sent_lists',
        ),
    ]
