# Generated by Django 5.2.8 on 2025-12-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_client_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, choices=[('lost', 'Lost'), ('won', 'Won')], max_length=50, null=True),
        ),
    ]
